### ISSUE TITLE
请问如何将主题强制配置成light模式

### ISSUE THREAD

**Issue by ccforeverd** [xrr2016/hexo-theme-cold-stone#11]
即不跟随mac系统

**Comment by xrr2016** [comment]
> 即不跟随mac系统

将 https://github.com/xrr2016/hexo-theme-cold-stone/blob/7e7a133049b722bdd899304a2dd6a9555500ecb1/source/styles/cold-stone.css#L891 这里的媒体查询样式注释中即可

**Comment by ccforeverd** [comment]
注掉了, OK了, 感谢这么快速的回复~
