### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by whataa** [xrr2016/hexo-theme-cold-stone#2]
主题很棒，感谢作者，体验了一下暂时归纳了几个希望优化的点：

1. 列表的每一项任意地方都可以响应点击进入详情而不仅仅是”阅读全文“；
2. 内容页可以再宽一点；
3. 发布时间因为标签的原因没对齐，不知道有什么更好的方案；

**Comment by xrr2016** [comment]
> 主题很棒，感谢作者，体验了一下暂时归纳了几个希望优化的点：
> 
> 1. 列表的每一项任意地方都可以响应点击进入详情而不仅仅是”阅读全文“；
> 2. 内容页可以再宽一点；
> 3. 发布时间因为标签的原因没对齐，不知道有什么更好的方案；

感谢建议，准备周末更新一波主题

**Comment by xrr2016** [comment]
> > 主题很棒，感谢作者，体验了一下暂时归纳了几个希望优化的点：
> > 
> > 1. 列表的每一项任意地方都可以响应点击进入详情而不仅仅是”阅读全文“；
> > 2. 内容页可以再宽一点；
> > 3. 发布时间因为标签的原因没对齐，不知道有什么更好的方案；
> 
> 感谢建议，准备周末更新一波主题

主题更新啦！可以查看本次更新的变化 https://github.com/xrr2016/hexo-theme-cold-stone/blob/master/README-zh.md#%E5%8F%91%E5%B8%83%E6%97%A5%E5%BF%97

**Comment by wuyiwai** [comment]
Hi,试用发现了几处报错.
```
Unhandled rejection ReferenceError: /testFolder/themes/cold-stone/layout/index.ejs:71
    69|         </div>
    70|         <div class="card">
 >> 71|             <p class="subtitle">博客总字数&#58; <%= totalcount(site) %></p>
    72|         </div>
    73|     </aside>
    74| </section>

totalcount is not defined
    at eval (eval at compile (/testFolder/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:130:7)
    at returnedFn (/testFolder/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (/testFolder/node_modules/hexo/lib/theme/view.js:123:48)
    at Theme._View.View.View.render (/testFolder/node_modules/hexo/lib/theme/view.js:29:15)
    at /testFolder/node_modules/hexo/lib/hexo/index.js:349:21
    at tryCatcher (/testFolder/node_modules/bluebird/js/release/util.js:16:23)
    at /testFolder/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/testFolder/node_modules/hexo/lib/hexo/router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:933:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)


Cannot read property 'repo' of undefined
TypeError: /testFolder/themes/cold-stone/layout/layout.ejs:15
    13|     <% } %>
    14| 
 >> 15|     <%- partial('_partial/script', null, {cache: false}) %>
    16|   </body>
    17| </html>
    18| 

/testFolder/themes/cold-stone/layout/_partial/script.ejs:3
    1| <script>
    2|  window.COLD_STONE = {
 >> 3|    repo: "<%- config.comment.repo %>",
    4|    gaid: "<%- config.track.gaid %>"
    5|  }
    6| </script>
```

**Comment by xrr2016** [comment]
> Hi,试用发现了几处报错.
> 
> ```
> Unhandled rejection ReferenceError: /testFolder/themes/cold-stone/layout/index.ejs:71
>     69|         </div>
>     70|         <div class="card">
>  >> 71|             <p class="subtitle">博客总字数&#58; <%= totalcount(site) %></p>
>     72|         </div>
>     73|     </aside>
>     74| </section>
> 
> totalcount is not defined
>     at eval (eval at compile (/testFolder/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:130:7)
>     at returnedFn (/testFolder/node_modules/ejs/lib/ejs.js:668:17)
>     at Theme._View.View._compiled.locals [as _compiled] (/testFolder/node_modules/hexo/lib/theme/view.js:123:48)
>     at Theme._View.View.View.render (/testFolder/node_modules/hexo/lib/theme/view.js:29:15)
>     at /testFolder/node_modules/hexo/lib/hexo/index.js:349:21
>     at tryCatcher (/testFolder/node_modules/bluebird/js/release/util.js:16:23)
>     at /testFolder/node_modules/bluebird/js/release/method.js:15:34
>     at RouteStream._read (/testFolder/node_modules/hexo/lib/hexo/router.js:123:3)
>     at RouteStream.Readable.read (_stream_readable.js:457:10)
>     at resume_ (_stream_readable.js:933:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> 
> 
> Cannot read property 'repo' of undefined
> TypeError: /testFolder/themes/cold-stone/layout/layout.ejs:15
>     13|     <% } %>
>     14| 
>  >> 15|     <%- partial('_partial/script', null, {cache: false}) %>
>     16|   </body>
>     17| </html>
>     18| 
> 
> /testFolder/themes/cold-stone/layout/_partial/script.ejs:3
>     1| <script>
>     2|  window.COLD_STONE = {
>  >> 3|    repo: "<%- config.comment.repo %>",
>     4|    gaid: "<%- config.track.gaid %>"
>     5|  }
>     6| </script>
> ```

我忘记写 README 了... 上面的报错一个是需要在博客仓库安装 hexo-wordcount 这个库，用来统计字数的，然后是评论系统需要在 _config.yml 里配置你的博客的 github 仓库地址
```yml
comment:
  repo: xrr2016/blog
```

**Comment by wuyiwai** [comment]
感谢！

**Comment by whataa** [comment]
你好，完全按照readme的步骤依然无法使用：
```
➜  testHexo hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR Render HTML failed: index.html
TypeError: /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/layout.ejs:15
    13|     <% } %>
    14|
 >> 15|     <%- partial('_partial/script', null, {cache: false}) %>
    16|   </body>
    17| </html>
    18|

/Users/XXX/Downloads/testHexo/themes/cold-stone/layout/_partial/script.ejs:3
    1| <script>
    2| 	window.COLD_STONE = {
 >> 3| 	  repo: "<%- config.comment.repo %>",
    4| 	  gaid: "<%- config.track.gaid %>"
    5| 	}
    6| </script>

Cannot read property 'repo' of undefined
    at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:32)
    at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:119:22)
    at Theme._View.View.View.renderSync (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:38:17)
    at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:123:48)
    at Theme._View.View.View.render (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:29:15)
    at _compiled.then.result (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:40:23)
    at tryCatcher (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
Unhandled rejection TypeError: /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/layout.ejs:15
    13|     <% } %>
    14|
 >> 15|     <%- partial('_partial/script', null, {cache: false}) %>
    16|   </body>
    17| </html>
    18|

/Users/XXX/Downloads/testHexo/themes/cold-stone/layout/_partial/script.ejs:3
    1| <script>
    2| 	window.COLD_STONE = {
 >> 3| 	  repo: "<%- config.comment.repo %>",
    4| 	  gaid: "<%- config.track.gaid %>"
    5| 	}
    6| </script>

Cannot read property 'repo' of undefined
    at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:32)
    at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:119:22)
    at Theme._View.View.View.renderSync (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:38:17)
    at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:123:48)
    at Theme._View.View.View.render (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:29:15)
    at _compiled.then.result (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:40:23)
    at tryCatcher (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)

^CINFO  Have a nice day
```

**Comment by xrr2016** [comment]
> 你好，完全按照readme的步骤依然无法使用：
> 
> ```
> ➜  testHexo hexo s
> INFO  Start processing
> INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
> ERROR Render HTML failed: index.html
> TypeError: /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/layout.ejs:15
>     13|     <% } %>
>     14|
>  >> 15|     <%- partial('_partial/script', null, {cache: false}) %>
>     16|   </body>
>     17| </html>
>     18|
> 
> /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/_partial/script.ejs:3
>     1| <script>
>     2| 	window.COLD_STONE = {
>  >> 3| 	  repo: "<%- config.comment.repo %>",
>     4| 	  gaid: "<%- config.track.gaid %>"
>     5| 	}
>     6| </script>
> 
> Cannot read property 'repo' of undefined
>     at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:32)
>     at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
>     at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:119:22)
>     at Theme._View.View.View.renderSync (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:48:23)
>     at Object.partial (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
>     at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:38:17)
>     at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
>     at Theme._View.View._compiled.locals [as _compiled] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:123:48)
>     at Theme._View.View.View.render (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:29:15)
>     at _compiled.then.result (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:40:23)
>     at tryCatcher (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:517:31)
>     at Promise._settlePromise (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:574:18)
>     at Promise._settlePromise0 (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:619:10)
>     at Promise._settlePromises (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:699:18)
>     at _drainQueueStep (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:138:12)
>     at _drainQueue (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:131:9)
>     at Async._drainQueues (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:147:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:756:18)
>     at tryOnImmediate (timers.js:717:5)
>     at processImmediate [as _immediateCallback] (timers.js:697:5)
> Unhandled rejection TypeError: /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/layout.ejs:15
>     13|     <% } %>
>     14|
>  >> 15|     <%- partial('_partial/script', null, {cache: false}) %>
>     16|   </body>
>     17| </html>
>     18|
> 
> /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/_partial/script.ejs:3
>     1| <script>
>     2| 	window.COLD_STONE = {
>  >> 3| 	  repo: "<%- config.comment.repo %>",
>     4| 	  gaid: "<%- config.track.gaid %>"
>     5| 	}
>     6| </script>
> 
> Cannot read property 'repo' of undefined
>     at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:32)
>     at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
>     at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:119:22)
>     at Theme._View.View.View.renderSync (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:48:23)
>     at Object.partial (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
>     at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:38:17)
>     at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
>     at Theme._View.View._compiled.locals [as _compiled] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:123:48)
>     at Theme._View.View.View.render (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:29:15)
>     at _compiled.then.result (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:40:23)
>     at tryCatcher (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:517:31)
>     at Promise._settlePromise (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:574:18)
>     at Promise._settlePromise0 (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:619:10)
>     at Promise._settlePromises (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:699:18)
>     at _drainQueueStep (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:138:12)
>     at _drainQueue (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:131:9)
>     at Async._drainQueues (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:147:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:756:18)
>     at tryOnImmediate (timers.js:717:5)
>     at processImmediate [as _immediateCallback] (timers.js:697:5)
> 
> ^CINFO  Have a nice day
> ```

要设置 _config.yml 里面的 repo 变量
```yml
comment:
  repo: xrr2016/blog
```

**Comment by xrr2016** [comment]
> > 你好，完全按照readme的步骤依然无法使用：
> > ```
> > ➜  testHexo hexo s
> > INFO  Start processing
> > INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
> > ERROR Render HTML failed: index.html
> > TypeError: /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/layout.ejs:15
> >     13|     <% } %>
> >     14|
> >  >> 15|     <%- partial('_partial/script', null, {cache: false}) %>
> >     16|   </body>
> >     17| </html>
> >     18|
> > 
> > /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/_partial/script.ejs:3
> >     1| <script>
> >     2| 	window.COLD_STONE = {
> >  >> 3| 	  repo: "<%- config.comment.repo %>",
> >     4| 	  gaid: "<%- config.track.gaid %>"
> >     5| 	}
> >     6| </script>
> > 
> > Cannot read property 'repo' of undefined
> >     at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:32)
> >     at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
> >     at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:119:22)
> >     at Theme._View.View.View.renderSync (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:48:23)
> >     at Object.partial (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
> >     at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:38:17)
> >     at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
> >     at Theme._View.View._compiled.locals [as _compiled] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:123:48)
> >     at Theme._View.View.View.render (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:29:15)
> >     at _compiled.then.result (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:40:23)
> >     at tryCatcher (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/util.js:16:23)
> >     at Promise._settlePromiseFromHandler (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:517:31)
> >     at Promise._settlePromise (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:574:18)
> >     at Promise._settlePromise0 (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:619:10)
> >     at Promise._settlePromises (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:699:18)
> >     at _drainQueueStep (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:138:12)
> >     at _drainQueue (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:131:9)
> >     at Async._drainQueues (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:147:5)
> >     at Immediate.Async.drainQueues [as _onImmediate] (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:17:14)
> >     at runCallback (timers.js:756:18)
> >     at tryOnImmediate (timers.js:717:5)
> >     at processImmediate [as _immediateCallback] (timers.js:697:5)
> > Unhandled rejection TypeError: /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/layout.ejs:15
> >     13|     <% } %>
> >     14|
> >  >> 15|     <%- partial('_partial/script', null, {cache: false}) %>
> >     16|   </body>
> >     17| </html>
> >     18|
> > 
> > /Users/XXX/Downloads/testHexo/themes/cold-stone/layout/_partial/script.ejs:3
> >     1| <script>
> >     2| 	window.COLD_STONE = {
> >  >> 3| 	  repo: "<%- config.comment.repo %>",
> >     4| 	  gaid: "<%- config.track.gaid %>"
> >     5| 	}
> >     6| </script>
> > 
> > Cannot read property 'repo' of undefined
> >     at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:32)
> >     at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
> >     at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:119:22)
> >     at Theme._View.View.View.renderSync (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:48:23)
> >     at Object.partial (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
> >     at eval (eval at compile (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:38:17)
> >     at returnedFn (/Users/XXX/Downloads/testHexo/node_modules/ejs/lib/ejs.js:668:17)
> >     at Theme._View.View._compiled.locals [as _compiled] (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:123:48)
> >     at Theme._View.View.View.render (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:29:15)
> >     at _compiled.then.result (/Users/XXX/Downloads/testHexo/node_modules/hexo/lib/theme/view.js:40:23)
> >     at tryCatcher (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/util.js:16:23)
> >     at Promise._settlePromiseFromHandler (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:517:31)
> >     at Promise._settlePromise (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:574:18)
> >     at Promise._settlePromise0 (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:619:10)
> >     at Promise._settlePromises (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/promise.js:699:18)
> >     at _drainQueueStep (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:138:12)
> >     at _drainQueue (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:131:9)
> >     at Async._drainQueues (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:147:5)
> >     at Immediate.Async.drainQueues [as _onImmediate] (/Users/XXX/Downloads/testHexo/node_modules/bluebird/js/release/async.js:17:14)
> >     at runCallback (timers.js:756:18)
> >     at tryOnImmediate (timers.js:717:5)
> >     at processImmediate [as _immediateCallback] (timers.js:697:5)
> > 
> > ^CINFO  Have a nice day
> > ```
> 
> 要设置 _config.yml 里面的 repo 变量
> 
> ```yaml
> comment:
>   repo: xrr2016/blog
> ```

或者可以把它设置为可选项

**Comment by whataa** [comment]
OK 谢谢
