### ISSUE TITLE
WARN  No layout: index.html

### ISSUE THREAD

**Issue by zhhqiang3** [xrr2016/hexo-theme-cold-stone#4]
我尝试使用了一下 
结果 出现 no layout index.html 
主题目录下配置文件是空的 是这个原因吗？

![image](https://user-images.githubusercontent.com/20870394/65734164-52fde300-e104-11e9-8257-c89996012264.png)

**Comment by xrr2016** [comment]
> 我尝试使用了一下
> 结果 出现 no layout index.html
> 主题目录下配置文件是空的 是这个原因吗？
> 
> ![image](https://user-images.githubusercontent.com/20870394/65734164-52fde300-e104-11e9-8257-c89996012264.png)

😯这是我没遇到的情况...

**Comment by zhhqiang3** [comment]
是缺少配置吗？
