### ISSUE TITLE
bug : 移动端无法显示Home Index Page

### ISSUE THREAD

**Issue by togo13duke** [xrr2016/hexo-theme-cold-stone#8]
iPhone 的 Safari 和 Chrome 无法显示Home页面

* Chrome
![image](https://user-images.githubusercontent.com/23131516/66469387-b4d62980-eac2-11e9-8119-4f1c1649adbb.png)

* Safari
![image](https://user-images.githubusercontent.com/23131516/66469364-aa1b9480-eac2-11e9-92f1-9a933cae35be.png)

**Comment by xrr2016** [comment]
> iPhone 的 Safari 和 Chrome 无法显示Home页面
> 
> * Chrome
>   ![image](https://user-images.githubusercontent.com/23131516/66469387-b4d62980-eac2-11e9-8119-4f1c1649adbb.png)
> * Safari
>   ![image](https://user-images.githubusercontent.com/23131516/66469364-aa1b9480-eac2-11e9-92f1-9a933cae35be.png)

😅 其实页面是打开了，但是有一个首页的动画画布把内容遮挡了，看起来就好像没打开一样，貌似是 canvas 的兼容性问题，安卓手机没这个问题...

**Comment by xrr2016** [comment]
看来还要判断下如果是 iPhone 就不显示这个动画了...

**Comment by xrr2016** [comment]
> 看来还要判断下如果是 iPhone 就不显示这个动画了...

![image](https://user-images.githubusercontent.com/18013127/66477460-c1f71680-eaca-11e9-9dad-b33948e1a484.png)

safari 打开复现，原来是代码压缩的问题

**Comment by xrr2016** [comment]
发了个新版本修复了这个 BUG

**Comment by togo13duke** [comment]
>发了个新版本修复了这个 BUG

iPhone 的 Safari 和 Chrome 还是不行😅
iOS 的 WebKit... orz

**Comment by xrr2016** [comment]
> > 发了个新版本修复了这个 BUG
> 
> iPhone 的 Safari 和 Chrome 还是不行😅
> iOS 的 WebKit... orz

有缓存吧，我看我朋友的 iPhone 的 safari 上没问题了.

**Comment by togo13duke** [comment]
>有缓存吧，我看我朋友的 iPhone 的 safari 上没问题了.

啊呀，汗颜。
Tanks！！
